### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AndreaFan123**
Hello @cwpeng 

Kindly check the assignment for week 2, thank you :)

Link : http://44.198.225.149:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Your code load the same page many time when we scroll down to the bottom. You can use a global variable to trace API loading status. Set it to true at start of API loading, to false after end. Use it to make sure we load API only once at the same time.

**Comment by AndreaFan123** [comment]
Hello @cwpeng ,
I've revised my code ,kindly check, thank you.

Link : http://44.198.225.149:3000/

Screen Shot 2022-03-12 at 4 36 23 PM

**Comment by cwpeng** [comment]
Better. But, if I search 館, there should be 2 pages, but you will load up to 4 pages of all attractions.

**Comment by AndreaFan123** [comment]
Ok, let me check what causes that

**Comment by AndreaFan123** [comment]
Hello @cwpeng,
I've revised the code, kindly check, thank you.

Screen Shot 2022-03-12 at 4 36 23 PM

**Comment by cwpeng** [comment]
But, I cannot load page 2 when I search 館 and scroll down to the bottom.

**Comment by AndreaFan123** [comment]
Hello @cwpeng ,
Sorry it took me quite a long time to figure it out how to fix the issue. Kindly check if this is okay, thank you.

Link : http://44.198.225.149:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
