### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AndreaFan123**
Hello @cwpeng ,

Here is my week 3 assignment, kindly check the links below, thank you.

Link : 
Landing page :  http://44.198.225.149:3000/
attraction : http://44.198.225.149:3000/attraction/11

### CODE REVIEW

**Comment by AndreaFan123** [comment]
Hello @cwpeng ,
Kindly review my code when you are available, thank you.

**Comment by cwpeng** [comment]
1. Fill color of radio button should align with design.
2. I cannot switch back to first half day after I click second half day.

未命名-4

**Comment by AndreaFan123** [comment]
Hello @cwpeng,
I  have fixed both of the issues, kindly check, thank you.

http://44.198.225.149:3000/attraction/2
http://44.198.225.149:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
